### ISSUE TITLE
[EXPIRED] Page-based loading

### ISSUE THREAD

**Issue by sergeevabc** [BorisMoore/jsdefer#15]
There are a lot of JS loaders, really. But none of them, at least within documentation, addresses a problem I'm eager to solve. That is to use single  `<script>` line per whole project which inits page-based loading of dependencies.

Let's create a simple project with _index_, _portfolio_, and _contacts_ pages.

Microframework will help us with routing:

```
$app->get('/portfolio/',
    function () use ($app) {
        $prices = array(
              "price_mine"  => "90",
              "price_rival" => "120"
        );
        $app->render('portfolio.twig', $prices);
    });
```

Template engine will help us with rendering:

```
{% extends "base.twig" %}
{% block content %}
     <p>Aren't you sick and tired to pay {{price_rival}}…</p>.
{% endblock content %}
```

And the missing part in every page is `<script src="/static/init.js"></script>` that works as follows
- any page loads jQuery from CDN or from my server as fallback,
- _index_ loads SoundManager to serve audio salutation,
- _portfolio_ loads Lightbox to serve images,
- _contacts_ loads Forms validator.

What's the **best** way to achieve it?
And how to do that with **jsDefer** whether it's possible?

Thank you in advance.
Warm regards from Russia, Alexander.

**Comment by BorisMoore** [comment]
JsDefer allows you to declare dependencies, either declaratively as a "manifest", or through code, or on the actual scripts. Then you can have init.js declare your top-level dependencies and they will load along with their dependencies. See the ReadMe docs and examples...

**Comment by sergeevabc** [comment]
@BorisMoore, thank you for a quick reply, but RTFM is not a solution, but a runaround. :)

Let's make a tutorial example out of this question with _practical reply full of actual code_ that solves the problem.
You see, I'm just an end-user seeking for a way to simplify small projects management, so plain English is a winner.

**Comment by BorisMoore** [comment]
I'm not saying RTFM (assuming you did read it)! Just that I'm not sure what the problem is that is not solved by the manifest/dependency approach described. If you read about that approach and see it is missing a key feature, can you clarify - I am interested?

(BTW right now I am working hard to get JsRender and JsViews out to official beta and V1 - writing docs for etc. so having to give priority to that... I hope to get back to more documentation (and updates) on JsDefer at some point but it will be after JsViews hits V1.)

**Comment by sergeevabc** [comment]
@BorisMoore, as I understand, **jsDefer** has no built-in functionality to solve the problem.
But it's convenient to keep all rules in one file instead of writing lazyloads per page, isn't it?
So the core question is what's the best way to create conditional route system in `init.js`?

**Comment by sergeevabc** [comment]
@BorisMoore, so far I'm lucky to solve the case with LABjs!

1) Download _lab.min.js_.
2) Rename it to _init.js_.
3) Add `<script src="/js/init.js"></script>` into `<HEAD>` of all pages.
4) Add the following code inside _init.js_.  

```
...original lab.min.js goes here...

// Parse URL to get last argument before trailing slash as page name, or set / for root page
// e.g. http://domain.tld/portfolio/dell/ -> dell, http://domain.tld/ -> /
var path = location.pathname.split("/"),
    page = path[path.length-2] || "/";

// Scripts for all pages
$LAB
        .queueScript("/js/lib/jquery.js")
        .queueWait();

// Scripts per page
switch (page) {
    case '/':
        $LAB
        .queueScript("/js/lib/soundmanager2.js");
        break;
    case 'portfolio':
        $LAB
        .queueScript("/js/lib/lightbox.js");
        break;
    case 'contacts':
        $LAB
        .queueScript("/js/lib/forms.js");
        break;
}

// Load last instructions and execute the queue, cutie
$LAB
        .queueScript("/js/letsrock.js")
        .runQueue();
```

As you can see solution is basic, yet it serves the purpose without overhead of extra attributes and third-party routers.
Unfortunately it seems LABjs has not fallback functionality built-in, so, for example, jQuery fallback [turns into hell](https://gist.github.com/getify/670840).

As for **jsDefer**, is it possible to chain scripts and waits to run them in the end as shown above?

**Comment by BorisMoore** [comment]
Right - sorry, but JsDefer is not being actively maintained, so there are some open issues that I have not been able to get to. I'm not sure whether I will be able to resume active work on JsDefer in the future. (I would love to, but it is lower priority than JsViews and JsRender, for me... So it may not happen...)
