### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MathRobin** [BorisMoore/jsdefer#16]
Hello !

What about the license ? In which conditions can I use it ?

Thanks !

**Comment by BorisMoore** [comment]
Hello. 

JsDefer can be used according to the conditions of the MIT license, in the same way as is the case for JsViews, JsRender and JsObservable. 

I have added the license text to the project.

**Comment by BorisMoore** [comment]
@MathRobin: Your Js Loader comparison table looks great. 

BTW I notice you don't yet have data in there for jquery.defer.js, but only for jsdefer.js. Both should be working. There was a  bug on jquery.defer.js with the latest jquery versions, but it has been fixed. Let me know if you have any issues... Thanks!

**Comment by MathRobin** [comment]
I've integrated the MIT licence and added data for jquery.defer.js. Is it ok for you like this ? Don't hesitate to fix any mistake I did. Thanks for your work :)
