### ISSUE TITLE
URLs converted to lower case fail.

### ISSUE THREAD

**Issue by wforney** [BorisMoore/jsdefer#4]
In some cases, urls converted to lower case fail. The Azure CDN is case sensitive. This is hypo-critical. If you're going to build a case sensitive CDN you should build a loader that is case sensitive too. I'd rather have the CDN fixed but since that isn't likely to happen, the loader needs to play nice.

**Comment by BorisMoore** [comment]
We will fix this, to respect casing, but to do comparison (for identity) in a case-insensitive way.

**Comment by BorisMoore** [comment]
Fixed in https://github.com/BorisMoore/jsdefer/commit/08566695e0302afe3e850b34b2dea4b179253ccf
