### ISSUE TITLE
Should avoid duplicate references

### ISSUE THREAD

**Issue by wforney** [BorisMoore/jsdefer#6]
When including jsdefer.js on a page, if it is already loaded it should not load again or lose its references to what scripts are loaded already.

**Comment by wforney** [comment]
Also, placing the script tag for jsdefer.js in the body causes delayDomReady scenario to break. Placing in head works however.

**Comment by BorisMoore** [comment]
Fixed in https://github.com/BorisMoore/jsdefer/commit/fb993ed6c0fed8a824fc5f87d565f11a49f58520
