### ISSUE TITLE
chaining when().done().when().done()

### ISSUE THREAD

**Issue by wforney** [BorisMoore/jsdefer#8]
I happened across this post about chaining when().done() calls... It appears that it async loads everything and then chains the done methods together guaranteeing that they run in order. This seems more natural than having to nest a when() method inside a done() method to get this behavior. I might suggest adding this to jsdefer, or submitting to jQuery itself for inclusion...

http://www.bennadel.com/blog/2129-Experimenting-With-Sub-And-Deferred-Objects-In-jQuery-1-5.htm

**Comment by BorisMoore** [comment]
There is a new pipe method in [jquery-1.6b1](http://code.jquery.com/jquery-1.6b1.js)  which I think is along those lines. Haven't looked at it closely yet though...

**Comment by BorisMoore** [comment]
Closing, since should be covered by pipe.

**Comment by BorisMoore** [comment]
Closing, since should be covered by pipe.
